# Generated by Django 3.2.8 on 2021-10-31 14:37

from django.db import migrations, models
import emergency_contact.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daerah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='RumahSakit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=40)),
                ('alamat', models.CharField(max_length=60)),
                ('telepon', models.CharField(max_length=25, validators=[emergency_contact.models.validate_telepon])),
            ],
        ),
    ]
