# Generated by Django 3.2.8 on 2021-11-02 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daerah',
            old_name='nama',
            new_name='daerah',
        ),
        migrations.AddField(
            model_name='rumahsakit',
            name='daerah',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='emergency_contact.daerah'),
        ),
    ]
