# Generated by Django 3.2.8 on 2021-11-04 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_contact', '0002_auto_20211102_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daerah',
            name='daerah',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='rumahsakit',
            name='nama',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
